theme:
  name: material
  features:
    - navigation.sections # Sections are included in the navigation on the left.
    - toc.integrate # Table of contents is integrated on the left; does not appear separately on the right.
    - header.autohide # header disappears as you scroll
  palette:
    # Light mode / dark mode
    # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
    # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Lato
  icon:
    repo: fontawesome/brands/github # GitHub logo in top right
    # logo: "material/circle-opacity" # Equinox logo in top left
  # favicon: "_static/favicon.png"
  custom_dir: "_overrides" # Overriding part of the HTML

  # These additions are my own custom ones, having overridden a partial.
  twitter_name: "@avikpal1410"
  twitter_url: "https://twitter.com/avikpal1410"

# TODO(@avik-pal): Setup mkdocs for showing documentation versions
# extra:
#   version:
#     provider: mike

site_name: FluxMPI.jl
site_description: Documentation for FluxMPI.jl
site_author: Avik Pal
site_url: https://avik-pal.github.io/FluxMPI.jl/

repo_url: https://github.com/avik-pal/FluxMPI.jl
repo_name: avik-pal/FluxMPI.jl
edit_uri: "" # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: false # Don't allow warnings during the build process

extra_javascript:
  # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _static/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/custom.css
  - assets/Documenter.css

markdown_extensions:
  - admonition
  - toc:
      permalink: "¤" # Adds a clickable permalink to each section heading
      toc_depth: 4
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html


plugins:
  - search # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs # Cross-links to headings
  - include_exclude_files:
      exclude:
        - "_overrides"
  - mknotebooks # Jupyter notebooks

nav:
  - "FluxMPI.jl: Distributed Data Parallel Training of Neural Networks": "index.md"
  - "Examples":
    - "Usage with Lux": "examples/lux.md"
  - "Manual":
    - "Usage Guide": "guide.md"
    - "API Reference": "api.md"
    - "Common Gotchas": "common_gotchas.md"
